import json
import os


class HTMLReporter:

    def __init__(self, domain, results):

        self.domain = domain

        self.results = results

        self.output_dir = "output"

    def generate(self):

        os.makedirs(
            self.output_dir,
            exist_ok=True
        )

        filename = (
            f"{self.output_dir}/"
            f"{self.domain}_report.html"
        )

        html = f"""

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<title>
HEXSCAN REPORT
</title>

<style>

body {{

    background: #0d1117;

    color: #c9d1d9;

    font-family: Arial;

    margin: 40px;
}}

h1 {{

    color: #58a6ff;
}}

h2 {{

    color: #79c0ff;

    border-bottom: 1px solid #30363d;

    padding-bottom: 5px;
}}

.card {{

    background: #161b22;

    border: 1px solid #30363d;

    border-radius: 10px;

    padding: 20px;

    margin-bottom: 20px;
}}

pre {{

    white-space: pre-wrap;

    word-wrap: break-word;

    background: #0d1117;

    padding: 15px;

    border-radius: 8px;

    overflow-x: auto;
}}

.critical {{

    color: #ff4d4d;
}}

.high {{

    color: #ff884d;
}}

.medium {{

    color: #ffd24d;
}}

.low {{

    color: #4dff88;
}}

.footer {{

    margin-top: 40px;

    color: #8b949e;

    text-align: center;
}}

</style>

</head>

<body>

<h1>
HEXSCAN Recon Report
</h1>

<div class="card">

<b>Target:</b> {self.domain}<br>

<b>Modules:</b> {len(self.results)}<br>

</div>

"""

        # -----------------------------
        # RISK ANALYSIS
        # -----------------------------

        risk = self.results.get(
            "risk_analysis",
            {}
        )

        if risk:

            level = risk.get(
                "risk_level",
                "Low"
            ).lower()

            html += f"""

<div class="card">

<h2>
Risk Analysis
</h2>

<p>

<b>Risk Score:</b>
{risk.get("risk_score", 0)}

</p>

<p>

<b>Risk Level:</b>

<span class="{level}">
{risk.get("risk_level", "Low")}
</span>

</p>

<pre>
{json.dumps(risk.get("findings", []), indent=4)}
</pre>

</div>

"""

        # -----------------------------
        # RESULTS
        # -----------------------------

        for key, value in self.results.items():

            html += f"""

<div class="card">

<h2>
{key.upper()}
</h2>

<pre>
{json.dumps(value, indent=4, default=str)}
</pre>

</div>

"""

        html += """

<div class="footer">

Generated by HEXSCAN

</div>

</body>

</html>

"""

        with open(
            filename,
            "w",
            encoding="utf-8"
        ) as file:

            file.write(html)